services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    restart: unless-stopped
    env_file: ../../.env
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /secrets/jwt_secret.txt
      # AUTHELIA_SESSION_SECRET_FILE: /secrets/session_secret.txt
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /secrets/storage_encryption_key.txt
    volumes:
      - ${CONF_DIR}/authelia/config:/config
      - ${CONF_DIR}/authelia/secrets:/secrets:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.routers.authelia.rule=Host(`auth.${DOMAIN}`)
      - traefik.http.routers.authelia.tls.certresolver=cloudflare
      - traefik.http.services.authelia.loadbalancer.server.port=9091
      - traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/verify?rd=https://auth.benfeather.com/
      - traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Email,Remote-Name
