services:
  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    restart: unless-stopped
    env_file: 
      - ../../.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)
 